name: BullsEye
description: Your First Flutter App
dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.13.0+1
  stacked: ^1.2.2
  auto_route:
  stacked_services:
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  auto_route_generator:

flutter:
  uses-material-design: true