name: BullsEye
description: Your First Flutter App
dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.13.0+1
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true